### ISSUE TITLE
`fmt/core.h` not found

### ISSUE THREAD

**Issue by krahlos** [friendlyanon/cmake-init#77] opened 2023-01-05 20:58 UTC
In a freshly create `cmake-init` project `#include <fmt/core.h>` throws a `fatal error: file not found`, see e.g. [here][1].

However, in the [`CMakeLists.txt`][2] the existence `fmt` library is properly checked with `find_package` and also the target link is done properly by `cmake-init`. 

The include is [simple][3] so this should not go wrong there.

What could possibly go wrong?

Again, thank you for your help 🍪 

[1]: https://github.com/krahlos/hello-cmake-init/actions/runs/3850271578/jobs/6560223315
[2]: https://github.com/krahlos/hello-cmake-init/blob/master/CMakeLists.txt#L60
[3]: https://github.com/krahlos/hello-cmake-init/blob/master/include/hello-cmake-init/hello-cmake-init.hpp#L6

**Comment by matheusgomes28** [comment] 2023-01-05 21:46
I've noticed this too. I feel like it's something outside of `cmake-init`s control.  AFAIK, only the `conan` build is failing, is that what you're using?

I'm still investigating this, but I'm coming to the conclusion that it's an issue with the conan toolchain. I'll update you here if I find the culprit 😆

**Comment by matheusgomes28** [comment] 2023-01-06 09:39
I hadn't read the file (now I have), but as a conan user the first thing I did was to install conan deps before configuring the project. As far as I can see in the presets, the deps and toolchain file get correctly placed under the `conan` directory. The issue is when you don't specify the build type for conan.

The `fmt` cmake config files generated by conan will (rightly so) only properly configure for `Release` as it's the default build type. Since most poeple are selecting the `dev` preset (as per your intro docs), then the conan build will fail as the dependencies will not be properly configured for `fmt`.

There's nothing wrong with that, but it should definitely be made clear that, if you're building with `CMAKE_BUILD_TYPE=Debug` (as per the `dev` preset), then you should make sure to pass the `-sbuild_type=Debug` to `conan install`.

Also, it seems like if you were to add a release preset, you would need to reinstall the conan dependencies with the proper build type, so if you're switching between debug and release, you would need to install the deps every time. Obviously, conan caches all it's builds so this doesn't take a while, but installing the `conan` dependencies by the build type (such as `conan/dev` or `conan/rel`) could avoid that issue for developers creating new user presets with different build types. Just an idea :)

But yeah @krahlos , make sure you're passing the build type to `conan install`.

**Comment by friendlyanon** [comment] 2023-01-06 10:01
Yes, the HACKING.md doc instructs the reader to install debug dependencies and build in debug mode. Different configs are not mixed by default in CMake.

**Comment by krahlos** [comment] 2023-01-06 11:22
Thank you for your hints 🍪 

Indeed I ensured that I had the dependencies installed correctly via `conan`, like it is explained in the `HACKING.md`. 

Calling `conan install . -s build_type=Debug -b missing` gives me the result shown below, so I assume that the dependencies have been installed correctly.

<details>

```
% conan install . -s build_type=Debug -b missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.libcxx=libc++
compiler.version=15
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
CC=clang-15
CXX=clang++
conanfile.py: Installing package
Requirements
    fmt/9.1.0 from 'conancenter' - Cache
Packages
    fmt/9.1.0:093285182398c6ab852fba193702346302f6d1a5 - Cache
Build requirements
    catch2/3.2.1 from 'conancenter' - Cache
Build requirements packages
    catch2/3.2.1:a1c11d3543e37b4ac3e888b9086140e20b53e93d - Cache

Installing (downloading, building) binaries...
catch2/3.2.1: Already installed!
fmt/9.1.0: Already installed!
conanfile.py: Applying build-requirement: catch2/3.2.1
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generator 'VirtualRunEnv' calling 'generate()'
conanfile.py: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py: Generator 'CMakeDeps' calling 'generate()'
conanfile.py: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py: Generator 'CMakeToolchain' calling 'generate()'
conanfile.py: Preset 'debug' added to CMakePresets.json. Invoke it manually using 'cmake --preset debug'
conanfile.py: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/path/to/hello-cmake-init/conan/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug'
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
```

</details>

As I'm a first-time `conan` user I also checked the steps of the [`sanitize`][1] job in my dummy project to ensure that I did not forget any of them.

Also I have deleted my `~/.conan` directory to ensure that the `debug` installation does not get messed up with any `release` installation from previous trials.

My `CMakeUserPresets.json` seem to be correct as well as I can now execute
```
cmake --preset=dev
cmake --build --preset=dev
ctest --preset=dev
```
without problems after the dependencies have been installed.

Still, this all does not explain to me why the linked [`sanitize`][1] job fails, as I assume that the [`ci.yl`][2] that is deployed by `cmake-init` is proper. Like mentioned in my previous ticket #76 I did not apply any changes to the initialization result of `cmake-init`, but only added the `hello_world()` function int the [`hello-cmake-init.hpp`][3] that I'm trying to call in the [`empty_example.cpp`][4].

[1]: https://github.com/krahlos/hello-cmake-init/actions/runs/3850271578/jobs/6560223315
[2]: https://github.com/krahlos/hello-cmake-init/blob/master/.github/workflows/ci.yml
[3]: https://github.com/krahlos/hello-cmake-init/blob/master/include/hello-cmake-init/hello-cmake-init.hpp#L11
[4]: https://github.com/krahlos/hello-cmake-init/blob/master/example/empty_example.cpp#L5

**Comment by friendlyanon** [comment] 2023-01-06 14:10
`fmt` is a [**build requirement**](https://github.com/krahlos/hello-cmake-init/blob/master/CMakeLists.txt#L61), but not a usage requirement.

You are impsing fmt as something that is required to use the library target, whereas the requirement specifier says that fmt is a build requirement. Some more details on this: https://gitlab.kitware.com/cmake/cmake/-/issues/23799

I'm going to close this, since the above has all the info here. You can also build with `-v` to see the build commands, which will tell you there is no include flag for fmt.

**Closed by friendlyanon** 2023-01-06 14:10 UTC
