### ISSUE TITLE
CMake ExternalProject addition as another package manager option?

### ISSUE THREAD

**Issue by tricktux** [friendlyanon/cmake-init#124] opened 2024-11-26 10:25 UTC
First: Thank you so much! Your project saved invaluable hours of my life.

However, I am finding myself with pulling the direction which may be non goals for you. Even though they are not explicitly mentioned.

But a native package manager would be great. By native I mean pull and build source.

Which is another goal I have to build for any platform with zig.

I've integrated zig semi successfully you can take a look at my [repo](https://github.com/tricktux/network-exercises)

Anyways main request:
- Extend for `ExternalProject` and/or `FetchContent`
Side request:
- Extend for using Zig as a build system

Thanks again!

**Comment by friendlyanon** [comment] 2024-11-26 14:50
You guessed right, EP/FC are really overused in scenarios where a package manager would be magnitudes more productive usually for reasons not immediately obvious, like isolation of builds, caching, reproducibility and portability.

For a Zig dependency to work, upstream would need to support clients using CMake and be available in one of the package managers. The former is easy, since that involves distributing 2 text files (`*Config.cmake` and `*ConfigVersion.cmake`) and the latter should be no biggie either, since both Conan and vcpkg are language agnostic. It sucks if upstream doesn't want to do the former and the latter can be easily worked around with a vcpkg overlay port, although you'll have to make sure the appropriate toolchains are reachable from the port.

I'll close this for now, since I'm not planning to change things, but you are welcome to open a Discussions thread regarding dependencies or join the C++ Slack's `cmake` channel regarding general CMake questions and integrating dependencies.

**Closed by friendlyanon** 2024-11-26 14:50 UTC
